"""add grid_image_path to shot_script

Revision ID: 018525ede92c
Revises: 2f44388844c3
Create Date: 2026-04-10 19:17:25.107020

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '018525ede92c'
down_revision = '2f44388844c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加九宫格图片路径字段
    op.add_column('shot_script', sa.Column('grid_image_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除九宫格图片路径字段
    op.drop_column('shot_script', 'grid_image_path')
    # ### end Alembic commands ###
