"""add scene grouping fields to ShotScript model

Revision ID: 2f44388844c3
Revises: 86d080593f6c
Create Date: 2026-04-05 15:02:45.237598

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f44388844c3'
down_revision = '86d080593f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs', if_exists=True)
    op.drop_table('checkpoint_blobs', if_exists=True)
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes', if_exists=True)
    op.drop_table('checkpoint_writes', if_exists=True)
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints', if_exists=True)
    op.drop_table('checkpoints', if_exists=True)
    op.drop_table('checkpoint_migrations', if_exists=True)
    
    # 添加场景分组字段 - 先允许为空
    op.add_column('shot_script', sa.Column('scene_group', sa.Integer(), nullable=True))
    op.add_column('shot_script', sa.Column('scene_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('shot_script', sa.Column('shot_group', sa.Integer(), nullable=True))
    
    # 更新现有数据：设置默认值
    # 使用 batch 参数避免在 PostgreSQL 中出现 "cannot update during a batch" 错误
    op.execute("""
        UPDATE shot_script 
        SET scene_group = 1, 
            scene_name = '默认场景', 
            shot_group = ((shot_no - 1) / 4) + 1
        WHERE scene_group IS NULL
    """)
    
    # 设置字段为 NOT NULL
    op.alter_column('shot_script', 'scene_group', nullable=False)
    op.alter_column('shot_script', 'scene_name', nullable=False)
    op.alter_column('shot_script', 'shot_group', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shot_script', 'shot_group')
    op.drop_column('shot_script', 'scene_name')
    op.drop_column('shot_script', 'scene_group')
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    # ### end Alembic commands ###
