"""add first_frame_image_path to shot_script

Revision ID: 3a5b7c9d1e2f
Revises: 2f44388844c3
Create Date: 2026-04-23 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '3a5b7c9d1e2f'
down_revision = 'a3b1c2d3e4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shot_script', sa.Column('first_frame_image_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shot_script', 'first_frame_image_path')
    # ### end Alembic commands ###
