"""add three table

Revision ID: 60ff8c82b608
Revises: af7db4be3da2
Create Date: 2026-03-09 19:41:35.170318

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60ff8c82b608'
down_revision = 'af7db4be3da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_log',
    sa.Column('target_type', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('operate_type', sa.Integer(), nullable=False),
    sa.Column('operate_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operate_user_id', sa.Uuid(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operate_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script',
    sa.Column('script_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('script_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('share_perm', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('last_editor_id', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['last_editor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_info',
    sa.Column('role_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('script_id', sa.Uuid(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['script.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shot_script',
    sa.Column('shot_no', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('total_script', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('script_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['character_info.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['script.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_created_at'), table_name='generated_images')
    op.drop_index(op.f('idx_prompt'), table_name='generated_images', postgresql_using='gin')
    op.drop_table('generated_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='图片URL地址'),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False, comment='生成图片使用的提示词'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('generated_images_pkey')),
    comment='存储生成的图片信息'
    )
    op.create_index(op.f('idx_prompt'), 'generated_images', [sa.literal_column("to_tsvector('english'::regconfig, prompt)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_created_at'), 'generated_images', ['created_at'], unique=False)
    op.drop_table('shot_script')
    op.drop_table('character_info')
    op.drop_table('script')
    op.drop_table('operation_log')
    # ### end Alembic commands ###
