"""add age field to user and new script related tables

Revision ID: 86d080593f6c
Revises: 60ff8c82b608
Create Date: 2026-03-26 21:02:13.666051

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '86d080593f6c'
down_revision = '60ff8c82b608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_info', sa.Column('three_view_image_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_info', 'three_view_image_path')
    # ### end Alembic commands ###
