"""add video_path to shot_script

Revision ID: a3b1c2d3e4f5
Revises: 74f92ae6c96c
Create Date: 2026-04-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = 'a3b1c2d3e4f5'
down_revision = '74f92ae6c96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shot_script', sa.Column('video_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shot_script', 'video_path')
    # ### end Alembic commands ###
